import React, { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Shopify Developer Challenge</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1
					className={styles.title}
					style={{ fontFamily: "Montserrat, sans-serif" }}
				>
					{`Welcome to Saqif Abrar's`}
					<span style={{ margin: "2.5% 0", color: "#95BF46" }}>
						<h1
							style={{ fontFamily: "Montserrat, sans-serif", fontSize: "6vw" }}
						>
							Shopify
						</h1>
					</span>
					{`Challenge!`}
				</h1>

				<p className={styles.description}>
					<code className={styles.code}>
						{`Hacker saqif = new Hacker("Saqif", "Abrar", "full-stack developer");`}
					</code>
					<br />
					{`I'm passionate about programming on all ends to become a more well
					rounded developer.`}
				</p>

				<div className={styles.grid}>
					<a href='/backend' className={styles.card}>
						<h2>Backend &rarr;</h2>
						<p>Shopify Backend Intern Challenge</p>
					</a>

					<a href='/frontend' className={styles.card}>
						<h2>Frontend &rarr;</h2>
						<p>Shopify Frontend Intern Challenge</p>
					</a>
				</div>
			</main>
		</div>
	);
}
