import React, { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Shopify Developer Challenge</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					{`Welcome to Saqif Abrar's Shopify Challenge!`}
				</h1>

				<p className={styles.description}>
					<code className={styles.code}>
						{`Hacker saqif = new Hacker("Saqif", "Abrar", "full-stack developer");`}
					</code>
					<br />
					{`I'm passionate about programming on all ends to become a more well
					rounded developer.`}
				</p>

				<div className={styles.grid}>
					<a href='' className={styles.card}>
						<h2>Backend &rarr;</h2>
						<p>{`Shopify Backend Intern Challenge <UPDATING>`}</p>
					</a>

					<a href='/frontend' className={styles.card}>
						<h2>Frontend &rarr;</h2>
						<p>Shopify Frontend Intern Challenge</p>
					</a>
				</div>
			</main>
		</div>
	);
}
